basic.forever(function () {
    led.setBrightness(199)
    led.plot(2, 4)
    basic.pause(100)
    led.plot(2, 3)
    basic.pause(200)
    led.plot(2, 2)
    basic.pause(200)
    led.plot(2, 1)
    basic.pause(100)
    led.plot(2, 0)
    led.setBrightness(255)
    basic.showIcon(IconNames.Heart)
    control.reset()
})
